import mock from '../mock'
import { paginateArray, sortCompare } from '../utils'

const data = {
  invoices: [
    {
      id: 4987,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Nike",
      releaseDate: '5 days',
      client: {
        address: '7777 Mendez Plains',
        company: 'Hall-Robbins PLC',
        companyEmail: 'don85@johnson.com',
        country: 'USA',
        contact: '(616) 865-4180',
        name: 'Jordan Stevenson'
      },
      service: 'Software Development',
      total: 3428,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Paid',
      balance: '$724',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '23 Apr 2019'
    },
    {
      id: 4988,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Naruto",
      releaseDate: '17 Jul 2019',
      client: {
        address: '04033 Wesley Wall Apt. 961',
        company: 'Mccann LLC and Sons',
        companyEmail: 'brenda49@taylor.info',
        country: 'Haiti',
        contact: '(226) 204-8287',
        name: 'Stephanie Burns'
      },
      service: 'UI/UX Design & Development',
      total: 5219,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/10-small.png').default,
      invoiceStatus: 'Downloaded',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '15 Dec 2019'
    },
    {
      id: 4989,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Naruto",
      releaseDate: '19 Oct 2019',
      client: {
        address: '5345 Robert Squares',
        company: 'Leonard-Garcia and Sons',
        companyEmail: 'smithtiffany@powers.com',
        country: 'Denmark',
        contact: '(955) 676-1076',
        name: 'Tony Herrera'
      },
      service: 'Unlimited Extended License',
      total: 3719,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/1-small.png').default,
      invoiceStatus: 'Paid',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '03 Nov 2019'
    },
    {
      id: 4990,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Naruto",
      releaseDate: '06 Mar 2020',
      client: {
        address: '19022 Clark Parks Suite 149',
        company: 'Smith, Miller and Henry LLC',
        companyEmail: 'mejiageorge@lee-perez.com',
        country: 'Cambodia',
        contact: '(832) 323-6914',
        name: 'Kevin Patton'
      },
      service: 'Software Development',
      total: 4749,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/9-small.png').default,
      invoiceStatus: 'Sent',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '11 Feb 2020'
    },
    {
      id: 4991,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Naruto",
      releaseDate: '08 Feb 2020',
      client: {
        address: '8534 Saunders Hill Apt. 583',
        company: 'Garcia-Cameron and Sons',
        companyEmail: 'brandon07@pierce.com',
        country: 'Martinique',
        contact: '(970) 982-3353',
        name: 'Mrs. Julie Donovan MD'
      },
      service: 'UI/UX Design & Development',
      total: 4056,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/10-small.png').default,
      invoiceStatus: 'Draft',
      balance: '$815',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '30 Jun 2019'
    },
    {
      id: 4992,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Naruto",
      releaseDate: '26 Aug 2019',
      client: {
        address: '661 Perez Run Apt. 778',
        company: 'Burnett-Young PLC',
        companyEmail: 'guerrerobrandy@beasley-harper.com',
        country: 'Botswana',
        contact: '(511) 938-9617',
        name: 'Amanda Phillips'
      },
      service: 'UI/UX Design & Development',
      total: 2771,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Paid',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '24 Jun 2019'
    },
    {
      id: 4993,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Kakashi",
      releaseDate: '17 Sep 2019',
      client: {
        address: '074 Long Union',
        company: 'Wilson-Lee LLC',
        companyEmail: 'williamshenry@moon-smith.com',
        country: 'Montserrat',
        contact: '(504) 859-2893',
        name: 'Christina Collier'
      },
      service: 'UI/UX Design & Development',
      total: 2713,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Draft',
      balance: '$407',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '22 Nov 2019'
    },
    {
      id: 4994,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Kakashi",
      releaseDate: '11 Feb 2020',
      client: {
        address: '5225 Ford Cape Apt. 840',
        company: 'Schwartz, Henry and Rhodes Group',
        companyEmail: 'margaretharvey@russell-murray.com',
        country: 'Oman',
        contact: '(758) 403-7718',
        name: 'David Flores'
      },
      service: 'Template Customization',
      total: 4309,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/9-small.png').default,
      invoiceStatus: 'Paid',
      balance: '-$205',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '10 Feb 2020'
    },
    {
      id: 4995,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Kakashi",
      releaseDate: '26 Jan 2020',
      client: {
        address: '23717 James Club Suite 277',
        company: 'Henderson-Holder PLC',
        companyEmail: 'dianarodriguez@villegas.com',
        country: 'Cambodia',
        contact: '(292) 873-8254',
        name: 'Valerie Perez'
      },
      service: 'Software Development',
      total: 3367,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/2-small.png').default,
      invoiceStatus: 'Downloaded',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '24 Dec 2019'
    },
    {
      id: 4996,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Kakashi",
      releaseDate: '15 Jan 2020',
      client: {
        address: '4528 Myers Gateway',
        company: 'Page-Wise PLC',
        companyEmail: 'bwilson@norris-brock.com',
        country: 'Guam',
        contact: '(956) 803-2008',
        name: 'Susan Dickerson'
      },
      service: 'Software Development',
      total: 4776,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/9-small.png').default,
      invoiceStatus: 'Downloaded',
      balance: '$305',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '02 Jun 2019'
    },
    {
      id: 4997,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Konan",
      releaseDate: '27 Sep 2019',
      client: {
        address: '4234 Mills Club Suite 107',
        company: 'Turner PLC Inc',
        companyEmail: 'markcampbell@bell.info',
        country: 'United States Virgin Islands',
        contact: '(716) 962-8635',
        name: 'Kelly Smith'
      },
      service: 'Unlimited Extended License',
      total: 3789,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/4-small.png').default,
      invoiceStatus: 'Partial Payment',
      balance: '$666',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '18 Mar 2020'
    },
    {
      id: 4998,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Konan",
      releaseDate: '31 Jul 2019',
      client: {
        address: '476 Keith Meadow',
        company: 'Levine-Dorsey PLC',
        companyEmail: 'mary61@rosario.com',
        country: 'Syrian Arab Republic',
        contact: '(523) 449-0782',
        name: 'Jamie Jones'
      },
      service: 'Unlimited Extended License',
      total: 5200,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/5-small.png').default,
      invoiceStatus: 'Partial Payment',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '17 Jan 2020'
    },
    {
      id: 4999,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Konan",
      releaseDate: '14 Feb 2020',
      client: {
        address: '56381 Ashley Village Apt. 332',
        company: 'Hall, Thompson and Ramirez LLC',
        companyEmail: 'sean22@cook.com',
        country: 'Ukraine',
        contact: '(583) 470-8356',
        name: 'Ruben Garcia'
      },
      service: 'Software Development',
      total: 4558,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/7-small.png').default,
      invoiceStatus: 'Paid',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '01 Oct 2019'
    },
    {
      id: 5000,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Konan",
      releaseDate: '21 May 2019',
      client: {
        address: '6946 Gregory Plaza Apt. 310',
        company: 'Lambert-Thomas Group',
        companyEmail: 'mccoymatthew@lopez-jenkins.net',
        country: 'Vanuatu',
        contact: '(366) 906-6467',
        name: 'Ryan Meyer'
      },
      service: 'Template Customization',
      total: 3503,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/9-small.png').default,
      invoiceStatus: 'Paid',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '22 May 2019'
    },
    {
      id: 5001,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Sarutobi",
      releaseDate: '30 Jun 2019',
      client: {
        address: '64351 Andrew Lights',
        company: 'Gregory-Haynes PLC',
        companyEmail: 'novakshannon@mccarty-murillo.com',
        country: 'Romania',
        contact: '(320) 616-3915',
        name: 'Valerie Valdez'
      },
      service: 'Unlimited Extended License',
      total: 5285,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/2-small.png').default,
      invoiceStatus: 'Partial Payment',
      balance: '-$202',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '02 Aug 2019'
    },
    {
      id: 5002,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: false,
      brand: "Sarutobi",
      releaseDate: '21 Jun 2019',
      client: {
        address: '5702 Sarah Heights',
        company: 'Wright-Schmidt LLC',
        companyEmail: 'smithrachel@davis-rose.net',
        country: 'Costa Rica',
        contact: '(435) 899-1963',
        name: 'Melissa Wheeler'
      },
      service: 'UI/UX Design & Development',
      total: 3668,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/6-small.png').default,
      invoiceStatus: 'Downloaded',
      balance: '$731',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '15 Dec 2019'
    },
    {
      id: 5003,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Sarutobi",
      releaseDate: '30 Dec 2019',
      client: {
        address: '668 Robert Flats',
        company: 'Russell-Abbott Ltd',
        companyEmail: 'scott96@mejia.net',
        country: 'Congo',
        contact: '(254) 399-4728',
        name: 'Alan Jimenez'
      },
      service: 'Unlimited Extended License',
      total: 4372,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Sent',
      balance: '-$344',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '17 Sep 2019'
    },
    {
      id: 5004,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Uchiha",
      releaseDate: '27 May 2019',
      client: {
        address: '55642 Chang Extensions Suite 373',
        company: 'Williams LLC Inc',
        companyEmail: 'cramirez@ross-bass.biz',
        country: 'Saint Pierre and Miquelon',
        contact: '(648) 500-4338',
        name: 'Jennifer Morris'
      },
      service: 'Template Customization',
      total: 3198,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/7-small.png').default,
      invoiceStatus: 'Partial Payment',
      balance: '-$253',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '16 Aug 2019'
    },
    {
      id: 5005,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Uchiha",
      releaseDate: '30 Jul 2019',
      client: {
        address: '56694 Eric Orchard',
        company: 'Hudson, Bell and Phillips PLC',
        companyEmail: 'arielberg@wolfe-smith.com',
        country: 'Uruguay',
        contact: '(896) 544-3796',
        name: 'Timothy Stevenson'
      },
      service: 'Unlimited Extended License',
      total: 5293,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Past Due',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '01 Aug 2019'
    },
    {
      id: 5006,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Uchiha",
      releaseDate: '10 Jun 2019',
      client: {
        address: '3727 Emma Island Suite 879',
        company: 'Berry, Gonzalez and Heath Inc',
        companyEmail: 'yrobinson@nichols.com',
        country: 'Israel',
        contact: '(236) 784-5142',
        name: 'Erik Hayden'
      },
      service: 'Template Customization',
      total: 5612,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/6-small.png').default,
      invoiceStatus: 'Downloaded',
      balance: '$883',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '12 Apr 2019'
    },
    {
      id: 5007,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Uchiha",
      releaseDate: '01 Feb 2020',
      client: {
        address: '953 Miller Common Suite 580',
        company: 'Martinez, Fuller and Chavez and Sons',
        companyEmail: 'tatejennifer@allen.net',
        country: 'Cook Islands',
        contact: '(436) 717-2419',
        name: 'Katherine Kennedy'
      },
      service: 'Software Development',
      total: 2230,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/1-small.png').default,
      invoiceStatus: 'Sent',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '19 Nov 2019'
    },
    {
      id: 5008,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Armani",
      releaseDate: '22 Mar 2020',
      client: {
        address: '808 Sullivan Street Apt. 135',
        company: 'Wilson and Sons LLC',
        companyEmail: 'gdurham@lee.com',
        country: 'Nepal',
        contact: '(489) 946-3041',
        name: 'Monica Fuller'
      },
      service: 'Unlimited Extended License',
      total: 2032,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/8-small.png').default,
      invoiceStatus: 'Partial Payment',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '30 Nov 2019'
    },
    {
      id: 5009,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Armani",
      releaseDate: '30 Nov 2019',
      client: {
        address: '25135 Christopher Creek',
        company: 'Hawkins, Johnston and Mcguire PLC',
        companyEmail: 'jenny96@lawrence-thompson.com',
        country: 'Kiribati',
        contact: '(274) 246-3725',
        name: 'Stacey Carter'
      },
      service: 'UI/UX Design & Development',
      total: 3128,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/3-small.png').default,
      invoiceStatus: 'Paid',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '10 Sep 2019'
    },
    {
      id: 5010,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Armani",
      releaseDate: '06 Jan 2020',
      client: {
        address: '81285 Rebecca Estates Suite 046',
        company: 'Huynh-Mills and Sons',
        companyEmail: 'jgutierrez@jackson.com',
        country: 'Swaziland',
        contact: '(258) 211-5970',
        name: 'Chad Davis'
      },
      service: 'Software Development',
      total: 2060,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/2-small.png').default,
      invoiceStatus: 'Downloaded',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '08 Dec 2019'
    },
    {
      id: 5011,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Armani",
      releaseDate: '01 Jun 2019',
      client: {
        address: '3102 Briggs Dale Suite 118',
        company: 'Jones-Cooley and Sons',
        companyEmail: 'hunter14@jones.com',
        country: 'Congo',
        contact: '(593) 965-4100',
        name: 'Chris Reyes'
      },
      service: 'UI/UX Design & Development',
      total: 4077,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Draft',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '01 Feb 2020'
    },
    {
      id: 5012,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Bata",
      releaseDate: '30 Oct 2019',
      client: {
        address: '811 Jill Skyway',
        company: 'Jones PLC Ltd',
        companyEmail: 'pricetodd@johnson-jenkins.com',
        country: 'Brazil',
        contact: '(585) 829-2603',
        name: 'Laurie Summers'
      },
      service: 'Template Customization',
      total: 2872,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/4-small.png').default,
      invoiceStatus: 'Partial Payment',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '18 Oct 2019'
    },
    {
      id: 5013,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Bata",
      releaseDate: '05 Feb 2020',
      client: {
        address: '2223 Brandon Inlet Suite 597',
        company: 'Jordan, Gomez and Ross Group',
        companyEmail: 'perrydavid@chapman-rogers.com',
        country: 'Congo',
        contact: '(527) 351-5517',
        name: 'Lindsay Wilson'
      },
      service: 'Software Development',
      total: 3740,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/10-small.png').default,
      invoiceStatus: 'Draft',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '01 Nov 2019'
    },
    {
      id: 5014,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Bata",
      releaseDate: '01 Dec 2019',
      client: {
        address: '08724 Barry Causeway',
        company: 'Gonzalez, Moody and Glover LLC',
        companyEmail: 'leahgriffin@carpenter.com',
        country: 'Equatorial Guinea',
        contact: '(628) 903-0132',
        name: 'Jenna Castro'
      },
      service: 'Unlimited Extended License',
      total: 3623,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Downloaded',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '23 Sep 2019'
    },
    {
      id: 5015,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Bata",
      releaseDate: '16 Apr 2019',
      client: {
        address: '073 Holt Ramp Apt. 755',
        company: 'Ashley-Pacheco Ltd',
        companyEmail: 'esparzadaniel@allen.com',
        country: 'Seychelles',
        contact: '(847) 396-9904',
        name: 'Wendy Weber'
      },
      service: 'Software Development',
      total: 2477,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/7-small.png').default,
      invoiceStatus: 'Draft',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '01 Apr 2019'
    },
    {
      id: 5016,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Nike",
      releaseDate: '24 Jan 2020',
      client: {
        address: '984 Sherry Trail Apt. 953',
        company: 'Berry PLC Group',
        companyEmail: 'todd34@owens-morgan.com',
        country: 'Ireland',
        contact: '(852) 249-4539',
        name: 'April Yates'
      },
      service: 'Unlimited Extended License',
      total: 3904,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Paid',
      balance: '$951',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '30 Sep 2019'
    },
    {
      id: 5017,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Nike",
      releaseDate: '24 Feb 2020',
      client: {
        address: '093 Jonathan Camp Suite 953',
        company: 'Allen Group Ltd',
        companyEmail: 'roydavid@bailey.com',
        country: 'Netherlands',
        contact: '(917) 984-2232',
        name: 'Daniel Marshall PhD'
      },
      service: 'UI/UX Design & Development',
      total: 3102,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/1-small.png').default,
      invoiceStatus: 'Partial Payment',
      balance: '-$153',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '25 Aug 2019'
    },
    {
      id: 5018,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Nike",
      releaseDate: '29 Feb 2020',
      client: {
        address: '4735 Kristie Islands Apt. 259',
        company: 'Chapman-Schneider LLC',
        companyEmail: 'baldwinjoel@washington.com',
        country: 'Cocos (Keeling) Islands',
        contact: '(670) 409-3703',
        name: 'Randy Rich'
      },
      service: 'UI/UX Design & Development',
      total: 2483,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/5-small.png').default,
      invoiceStatus: 'Draft',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '10 Jul 2019'
    },
    {
      id: 5019,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Nike",
      releaseDate: '07 Aug 2019',
      client: {
        address: '92218 Andrew Radial',
        company: 'Mcclure, Hernandez and Simon Ltd',
        companyEmail: 'psmith@morris.info',
        country: 'Macao',
        contact: '(646) 263-0257',
        name: 'Mrs. Jodi Chapman'
      },
      service: 'Unlimited Extended License',
      total: 2825,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/8-small.png').default,
      invoiceStatus: 'Partial Payment',
      balance: '-$459',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '14 Oct 2019'
    },
    {
      id: 5020,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Nike",
      releaseDate: '10 May 2019',
      client: {
        address: '2342 Michelle Valley',
        company: 'Hamilton PLC and Sons',
        companyEmail: 'lori06@morse.com',
        country: 'Somalia',
        contact: '(751) 213-4288',
        name: 'Steven Myers'
      },
      service: 'Unlimited Extended License',
      total: 2029,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/4-small.png').default,
      invoiceStatus: 'Past Due',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '28 Mar 2019'
    },
    {
      id: 5021,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Nike",
      releaseDate: '02 Apr 2019',
      client: {
        address: '16039 Brittany Terrace Apt. 128',
        company: 'Silva-Reeves LLC',
        companyEmail: 'zpearson@miller.com',
        country: 'Slovakia (Slovak Republic)',
        contact: '(655) 649-7872',
        name: 'Charles Alexander'
      },
      service: 'Software Development',
      total: 3208,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Sent',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '06 Sep 2019'
    },
    {
      id: 5022,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Nike",
      releaseDate: '02 May 2019',
      client: {
        address: '37856 Olsen Lakes Apt. 852',
        company: 'Solis LLC Ltd',
        companyEmail: 'strongpenny@young.net',
        country: 'Brazil',
        contact: '(402) 935-0735',
        name: 'Elizabeth Jones'
      },
      service: 'Software Development',
      total: 3077,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Sent',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '09 May 2019'
    },
    {
      id: 5023,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Nike",
      releaseDate: '23 Mar 2020',
      client: {
        address: '11489 Griffin Plaza Apt. 927',
        company: 'Munoz-Peters and Sons',
        companyEmail: 'carrietorres@acosta.com',
        country: 'Argentina',
        contact: '(915) 448-6271',
        name: 'Heidi Walton'
      },
      service: 'Software Development',
      total: 5578,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/9-small.png').default,
      invoiceStatus: 'Draft',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '23 Jul 2019'
    },
    {
      id: 5024,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Nike",
      releaseDate: '28 Sep 2019',
      client: {
        address: '276 Michael Gardens Apt. 004',
        company: 'Shea, Velez and Garcia LLC',
        companyEmail: 'zjohnson@nichols-powers.com',
        country: 'Philippines',
        contact: '(817) 700-2984',
        name: 'Christopher Allen'
      },
      service: 'Software Development',
      total: 2787,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/1-small.png').default,
      invoiceStatus: 'Partial Payment',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '25 Sep 2019'
    },
    {
      id: 5025,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Nike",
      releaseDate: '21 Feb 2020',
      client: {
        address: '633 Bell Well Apt. 057',
        company: 'Adams, Simmons and Brown Group',
        companyEmail: 'kayla09@thomas.com',
        country: 'Martinique',
        contact: '(266) 611-9482',
        name: 'Joseph Oliver'
      },
      service: 'UI/UX Design & Development',
      total: 5591,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Downloaded',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '07 Jun 2019'
    },
    {
      id: 5026,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Nike",
      releaseDate: '24 May 2019',
      client: {
        address: '1068 Lopez Fall',
        company: 'Williams-Lawrence and Sons',
        companyEmail: 'melvindavis@allen.info',
        country: 'Mexico',
        contact: '(739) 745-9728',
        name: 'Megan Roberts'
      },
      service: 'Template Customization',
      total: 2783,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/6-small.png').default,
      invoiceStatus: 'Draft',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '22 Oct 2019'
    },
    {
      id: 5027,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Nike",
      releaseDate: '13 Jan 2020',
      client: {
        address: '86691 Mackenzie Light Suite 568',
        company: 'Deleon Inc LLC',
        companyEmail: 'gjordan@fernandez-coleman.com',
        country: 'Costa Rica',
        contact: '(682) 804-6506',
        name: 'Mary Garcia'
      },
      service: 'Template Customization',
      total: 2719,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Sent',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '04 Feb 2020'
    },
    {
      id: 5028,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Nike",
      releaseDate: '18 May 2019',
      client: {
        address: '86580 Sarah Bridge',
        company: 'Farmer, Johnson and Anderson Group',
        companyEmail: 'robertscott@garcia.com',
        country: 'Cameroon',
        contact: '(775) 366-0411',
        name: 'Crystal Mays'
      },
      service: 'Template Customization',
      total: 3325,
      avatar1: require('@src/assets/images/logo/ss9.jpg').default,
      avatar: '',
      invoiceStatus: 'Paid',
      balance: '$361',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '02 Mar 2020'
    },
    {
      id: 5029,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Nike",
      releaseDate: '29 Oct 2019',
      client: {
        address: '49709 Edwin Ports Apt. 353',
        company: 'Sherman-Johnson PLC',
        companyEmail: 'desiree61@kelly.com',
        country: 'Macedonia',
        contact: '(510) 536-6029',
        name: 'Nicholas Tanner'
      },
      service: 'Template Customization',
      total: 3851,
      avatar1: require('@src/assets/images/logo/ss8.jpg').default,
      avatar: '',
      invoiceStatus: 'Paid',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '25 Aug 2019'
    },
    {
      id: 5030,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:false,
      sampling: false,
      brand: "Guccie",
      releaseDate: '07 Apr 2019',
      client: {
        address: '3856 Mathis Squares Apt. 584',
        company: 'Byrd LLC PLC',
        companyEmail: 'jeffrey25@martinez-hodge.com',
        country: 'Congo',
        contact: '(253) 230-4657',
        name: 'Mr. Justin Richardson'
      },
      service: 'Template Customization',
      total: 5565,
      avatar1: require('@src/assets/images/logo/ss7.jpg').default,
      avatar: '',
      invoiceStatus: 'Draft',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '06 Mar 2020'
    },
    {
      id: 5031,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Guccie",
      releaseDate: '21 Aug 2019',
      client: {
        address: '141 Adrian Ridge Suite 550',
        company: 'Stone-Zimmerman Group',
        companyEmail: 'john77@anderson.net',
        country: 'Falkland Islands (Malvinas)',
        contact: '(612) 546-3485',
        name: 'Jennifer Summers'
      },
      service: 'Template Customization',
      total: 3313,
      avatar1: require('@src/assets/images/logo/ss6.jpg').default,
      avatar: require('@src/assets/images/avatars/3-small.png').default,
      invoiceStatus: 'Partial Payment',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '09 Jun 2019'
    },
    {
      id: 5032,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Canvas",
      releaseDate: '31 May 2019',
      client: {
        address: '01871 Kristy Square',
        company: 'Yang, Hansen and Hart PLC',
        companyEmail: 'ywagner@jones.com',
        country: 'Germany',
        contact: '(203) 601-8603',
        name: 'Richard Payne'
      },
      service: 'Template Customization',
      total: 5181,
      avatar1: require('@src/assets/images/logo/ss5.jpg').default,
      avatar: '',
      invoiceStatus: 'Past Due',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '22 Oct 2019'
    },
    {
      id: 5033,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Nike",
      releaseDate: '12 Jul 2019',
      client: {
        address: '075 Smith Views',
        company: 'Jenkins-Rosales Inc',
        companyEmail: 'calvin07@joseph-edwards.org',
        country: 'Colombia',
        contact: '(895) 401-4255',
        name: 'Lori Wells'
      },
      service: 'Template Customization',
      total: 2869,
      avatar1: require('@src/assets/images/logo/ss4.jpg').default,
      avatar: require('@src/assets/images/avatars/1-small.png').default,
      invoiceStatus: 'Partial Payment',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '22 Mar 2020'
    },
    {
      id: 5034,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:false,
      inspection:true,
      sampling: true,
      brand: "Canvas",
      releaseDate: '10 Jul 2019',
      client: {
        address: '2577 Pearson Overpass Apt. 314',
        company: 'Mason-Reed PLC',
        companyEmail: 'eric47@george-castillo.com',
        country: 'Paraguay',
        contact: '(602) 336-9806',
        name: 'Tammy Sanchez'
      },
      service: 'Unlimited Extended License',
      total: 4836,
      avatar1: require('@src/assets/images/logo/ss3.jpg').default,
      avatar: '',
      invoiceStatus: 'Paid',
      balance: 0,
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '22 Oct 2019'
    },
    {
      id: 5035,
      SKU_ID: "#sku5643",
      Lead_time: '7 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:true,
      inspection:true,
      sampling: true,
      brand: "Bata",
      releaseDate: '20 Jul 2019',
      client: {
        address: '1770 Sandra Mountains Suite 636',
        company: 'Foster-Pham PLC',
        companyEmail: 'jamesjoel@chapman.net',
        country: 'Western Sahara',
        contact: '(936) 550-1638',
        name: 'Dana Carey'
      },
      service: 'UI/UX Design & Development',
      total: 4263,
      avatar1: require('@src/assets/images/logo/ss1.jpg').default,
      avatar: '',
      invoiceStatus: 'Draft',
      balance: '$762',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '12 Jun 2019'
    },
    {
      id: 5036,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      custom:false,
      inspection:true,
      sampling: true,
      brand: "Nike",
      releaseDate: '19 Apr 2019',
      client: {
        address: '78083 Laura Pines',
        company: 'Richardson and Sons LLC',
        companyEmail: 'pwillis@cross.org',
        country: 'Bhutan',
        contact: '(687) 660-2473',
        name: 'Andrew Burns'
      },
      service: 'Unlimited Extended License',
      total: 3171,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/9-small.png').default,
      invoiceStatus: 'Paid',
      balance: '-$205',
      buyer : 'TCS',
      seller : 'Retailsnet',
      dueDate: '25 Sep 2019'
    }
  ]
}

// ------------------------------------------------
// GET: Return Invoice List
// ------------------------------------------------
let duplicates = 0
duplicates = {}
Array.prototype.getDuplicates = function () {
    let i = 0
    while (i < this.length) {
        if (duplicates.hasOwnProperty(this[i].brand)) {
            duplicates[this[i].brand].push(this[i])
        } else if (this.lastIndexOf(this[i].brand) !== i) {
            duplicates[this[i].brand] = [this[i]]
        }
        i++
    }

    return duplicates
}

mock.onGet('/apps/invoice/invoices').reply(config => {
  // eslint-disable-next-line object-curly-newline
  const { q = '', perPage = 10, page = 1, status = null } = config
  /* eslint-enable */
  data.invoices.getDuplicates()
  const queryLowered = q.toLowerCase()
  const filteredData = data.invoices
    .filter(
      invoice =>
        /* eslint-disable operator-linebreak, implicit-arrow-linebreak */
        (invoice.brand.toLowerCase().includes(queryLowered) ||
          invoice.client.name.toLowerCase().includes(queryLowered)) &&
          invoice.brand.toLowerCase() === (status.toLowerCase() || 
          invoice.brand.toLowerCase())
    )
    .sort(sortCompare('id'))
    .reverse()
  /* eslint-enable  */

  return [
    200,
    {
      allData: data.invoices,
      invoices: paginateArray(filteredData, perPage, page),
      filtered: duplicates,
      total: filteredData.length
    }
  ]
})

// ------------------------------------------------
// GET: Return Single Invoice
// ------------------------------------------------
mock.onGet(/\/api\/invoice\/invoices\/\d+/).reply(config => {
  // // Get event id from URL
  const invoiceId = Number(config.url.substring(config.url.lastIndexOf('/') + 1))

  const invoiceIndex = data.invoices.findIndex(e => e.id === invoiceId)
  const responseData = {
    invoice: data.invoices[invoiceIndex],
    paymentDetails: {
      totalDue: '$12,110.55',
      bankName: 'American Bank',
      country: 'United States',
      iban: 'ETD95476213874685',
      swiftCode: 'BR91905'
    }
  }
  return [200, responseData]
})

// ------------------------------------------------
// DELETE: Deletes Invoice
// ------------------------------------------------
mock.onDelete('/apps/invoice/delete').reply(config => {
  // Get invoice id from URL
  let invoiceId = config.id

  // Convert Id to number
  invoiceId = Number(invoiceId)

  const invoiceIndex = data.invoices.findIndex(t => t.id === invoiceId)
  data.invoices.splice(invoiceIndex, 1)

  return [200]
})

// ------------------------------------------------
// GET: Return Clients
// ------------------------------------------------
mock.onGet('/api/invoice/clients').reply(() => {
  const clients = data.invoices.map(invoice => invoice.client)
  return [200, clients.slice(0, 5)]
})
