import { ChevronDown,  X, Check } from 'react-feather'
import { Badge} from 'reactstrap'
//expot data
export const data = [
    {
      id: 4987,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      response: true,
      custom: "Logo On T-shirt",
      inspection:true,
      sampling: true,
      brand: "Nike",
      releaseDate: '5 days',
      client: {
        address: '7777 Mendez Plains',
        company: 'Hall-Robbins PLC',
        companyEmail: 'don85@johnson.com',
        country: 'USA',
        contact: '(616) 865-4180',
        name: 'Jordan Stevenson'
      },
      service: 'Software Development',
      total: 3428,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Paid',
      balance: '$724',
      dueDate: '23 Apr 2019'
    },
    {
      id: 4988,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      response: false,
      custom: "Logo On T-shirt",
      inspection:true,
      sampling: true,
      brand: "Naruto",
      releaseDate: '17 Jul 2019',
      client: {
        address: '04033 Wesley Wall Apt. 961',
        company: 'Mccann LLC and Sons',
        companyEmail: 'brenda49@taylor.info',
        country: 'Haiti',
        contact: '(226) 204-8287',
        name: 'Stephanie Burns'
      },
      service: 'UI/UX Design & Development',
      total: 5219,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/10-small.png').default,
      invoiceStatus: 'Downloaded',
      balance: 0,
      dueDate: '15 Dec 2019'
    },
    {
      id: 4989,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      response: false,
      custom: "Logo On T-shirt",
      inspection:true,
      sampling: true,
      brand: "Naruto",
      releaseDate: '19 Oct 2019',
      client: {
        address: '5345 Robert Squares',
        company: 'Leonard-Garcia and Sons',
        companyEmail: 'smithtiffany@powers.com',
        country: 'Denmark',
        contact: '(955) 676-1076',
        name: 'Tony Herrera'
      },
      service: 'Unlimited Extended License',
      total: 3719,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/1-small.png').default,
      invoiceStatus: 'Paid',
      balance: 0,
      dueDate: '03 Nov 2019'
    },
    {
      id: 4990,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      response: true,
      custom: "Logo On T-shirt",
      inspection:true,
      sampling: true,
      brand: "Naruto",
      releaseDate: '06 Mar 2020',
      client: {
        address: '19022 Clark Parks Suite 149',
        company: 'Smith, Miller and Henry LLC',
        companyEmail: 'mejiageorge@lee-perez.com',
        country: 'Cambodia',
        contact: '(832) 323-6914',
        name: 'Kevin Patton'
      },
      service: 'Software Development',
      total: 4749,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/9-small.png').default,
      invoiceStatus: 'Sent',
      balance: 0,
      dueDate: '11 Feb 2020'
    },
    {
      id: 4991,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      response: true,
      custom: "Logo On T-shirt",
      inspection:true,
      sampling: true,
      brand: "Naruto",
      releaseDate: '08 Feb 2020',
      client: {
        address: '8534 Saunders Hill Apt. 583',
        company: 'Garcia-Cameron and Sons',
        companyEmail: 'brandon07@pierce.com',
        country: 'Martinique',
        contact: '(970) 982-3353',
        name: 'Mrs. Julie Donovan MD'
      },
      service: 'UI/UX Design & Development',
      total: 4056,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/10-small.png').default,
      invoiceStatus: 'Draft',
      balance: '$815',
      dueDate: '30 Jun 2019'
    },
    {
      id: 4992,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      response: true,
      custom: "Logo On T-shirt",
      inspection:true,
      sampling: true,
      brand: "Naruto",
      releaseDate: '26 Aug 2019',
      client: {
        address: '661 Perez Run Apt. 778',
        company: 'Burnett-Young PLC',
        companyEmail: 'guerrerobrandy@beasley-harper.com',
        country: 'Botswana',
        contact: '(511) 938-9617',
        name: 'Amanda Phillips'
      },
      service: 'UI/UX Design & Development',
      total: 2771,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Paid',
      balance: 0,
      dueDate: '24 Jun 2019'
    },
    {
      id: 4993,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      response: true,
      custom: "Logo On T-shirt",
      inspection:true,
      sampling: true,
      brand: "Kakashi",
      releaseDate: '17 Sep 2019',
      client: {
        address: '074 Long Union',
        company: 'Wilson-Lee LLC',
        companyEmail: 'williamshenry@moon-smith.com',
        country: 'Montserrat',
        contact: '(504) 859-2893',
        name: 'Christina Collier'
      },
      service: 'UI/UX Design & Development',
      total: 2713,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: '',
      invoiceStatus: 'Draft',
      balance: '$407',
      dueDate: '22 Nov 2019'
    },
    {
      id: 4994,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      response: true,
      custom: "Logo On T-shirt",
      inspection:true,
      sampling: true,
      brand: "Kakashi",
      releaseDate: '11 Feb 2020',
      client: {
        address: '5225 Ford Cape Apt. 840',
        company: 'Schwartz, Henry and Rhodes Group',
        companyEmail: 'margaretharvey@russell-murray.com',
        country: 'Oman',
        contact: '(758) 403-7718',
        name: 'David Flores'
      },
      response: true,
      service: 'Template', 
      total: 4309,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/9-small.png').default,
      invoiceStatus: 'Paid',
      balance: '-$205',
      dueDate: '10 Feb 2020'
    },
    {
      id: 4995,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      response: true,
      custom: "Logo On T-shirt",
      inspection:true,
      sampling: true,
      brand: "Kakashi",
      releaseDate: '26 Jan 2020',
      client: {
        address: '23717 James Club Suite 277',
        company: 'Henderson-Holder PLC',
        companyEmail: 'dianarodriguez@villegas.com',
        country: 'Cambodia',
        contact: '(292) 873-8254',
        name: 'Valerie Perez'
      },
      service: 'Software Development',
      total: 3367,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/2-small.png').default,
      invoiceStatus: 'Downloaded',
      balance: 0,
      dueDate: '24 Dec 2019'
    },
    {
      id: 4996,
      SKU_ID: "#sku5643",
      Lead_time: '5 days',
      Rate: '5000',
      MOQ: '200pcs',
      BUIN:'#bidoya5462',
      response: true,
      custom: "Logo On T-shirt",
      inspection:true,
      sampling: true,
      brand: "Kakashi",
      releaseDate: '15 Jan 2020',
      client: {
        address: '4528 Myers Gateway',
        company: 'Page-Wise PLC',
        companyEmail: 'bwilson@norris-brock.com',
        country: 'Guam',
        contact: '(956) 803-2008',
        name: 'Susan Dickerson'
      },
      service: 'Software Development',
      total: 4776,
      avatar1: require('@src/assets/images/logo/ss2.jpg').default,
      avatar: require('@src/assets/images/avatars/9-small.png').default,
      invoiceStatus: 'Downloaded',
      balance: '$305',
      dueDate: '02 Jun 2019'
    }
  
]
