// User Name
// transaction
// balane

//expot data
export const data = [
      {
        id:1,
        orderId:'54643',
        invoice: '#2348',
        Bid: "#Bid3432",
        qt: "20K",
        Date: `21-11-2021`,
        name: "Tejas",
        budget: "200K",
        avatar:'',
        rating: 1,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"Logo of team"
       
      },
      {
        id:2,
        orderId:'54643',
        invoice: '#2348',
        Bid: "#Bid4432",
        qt: "21K",
        Date: `21-11-2021`,
        name: "Pravin",
        budget: "200K",
        avatar:"",
        rating: 7.85,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"differnt Color"
      },
      {
        id:3,
        orderId:'54643',
        invoice: '#2348',
        Bid: "#Bid3442",
        qt: "10K",
        Date: `21-11-2021`,
        name: "Komal",
        budget: "200K",
        avatar:"",
        rating: 6.75,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"Company WaterMark"
      },
      {
        id:4,
        orderId:'54643',
        invoice: '#2348',
        Bid: "#Bid3452",
        qt: "2K",
        Date: `21-11-2021`,
        name: "Mehul",
        budget: "200K",
        avatar:'',
        rating: 6.5,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"Logo of team"
      },
      {
        id:5,
        orderId:'54643',
        invoice: '#2348',
        Bid: "#Bid3433",
        qt: "0.4K",
        Date: `21-11-2021`,
        name: "Harpriya",
        budget: "200K",
        avatar:"",
        rating: 2,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"differnt Color"
      },
      {
        id:6,
        orderId:'54643',
        invoice: '#2348',
        Bid: "#Bid6432",
        qt: "4K",
        Date: `21-11-2021`,
        name: "Sneha",
        budget: "200K",
        avatar:"",
        rating: 9,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"Company WaterMark"
      },
      {
        id:7,
        orderId:'54643',
        invoice: '#2348',
        Bid: "#Bid7432",
        qt: "12K",
        Date: `21-11-2021`,
        name: "Vijay",
        budget: "200K",
        avatar:"",
        rating: 10,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"Company WaterMark"
      },
      {
        id:8,
        orderId:'54643',
        invoice: '#2348',
        Bid: "#Bid3452",
        qt: "210K",
        Date: `21-11-2021`,
        name: "Vanita",
        budget: "200K",
        avatar:"",
        rating: 2,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"Logo of team"
      },
      {
        id:9,
        orderId:'54643',
        invoice: '#2348',
        Bid: "#Bid3672",
        qt: "30K",
        Date: `21-11-2021`,
        name: "Dhavde",
        budget: "200K",
        avatar:"",
        rating: 2.0,
        transaction: 200000,
        balance: 30000,
        review: "Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"Company WaterMark"
      }
]
