export const data1 = [
    {

          id:1,
          outOfOffice : "Pravin Poshmani",
          from : "12-11-2020",
          to : "14-11-2020",
          backUp : "Tejas Thakare"
    
    },
    {
        id:2,
        outOfOffice : "Tejas Thakare",
        from : "05-05-2021",
        to : "11-05-2021",
        backUp : "Pravin Poshmani"
    },
    {
        id:3,
        outOfOffice : "Komal Kamble",
        from : "12-10-2020",
        to : "14-12-2020",
        backUp : "Himanshu Chanda"
    },
    {
        id:4,
        outOfOffice : "Reethika",
        from : "10-11-2020",
        to : "19-11-2020",
        backUp : "Daksh"
    },
    {
        id:5,
        outOfOffice : "Himanshu Chanda",
        from : "12-11-2020",
        to : "14-11-2020",
        backUp : "Umang Shah"
    }
  ]


export const data = [
      {
        id:1,
        backup: 'Pravin Patil',
        role: 'Admin',
        email: "bidoya@gmail.com",
        Bid: "#Bid3432",
        qt: "20K",
        Date: `21-11-2021`,
        Date2: `12-01-2021`,
        name: "Tejas",
        budget: "200K",
        avatar:'',
        rating: 1,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"Logo of team"
       
      },
      {
        id:2,
        backup: 'Komal Jadhav',
        role: 'Employee',
        email: "bidoya1@gmail.com",
        Bid: "#Bid4432",
        qt: "21K",
        Date: `21-11-2021`,
        Date2: `12-01-2021`,
        name: "Pravin",
        budget: "200K",
        avatar:"",
        rating: 7.85,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"differnt Color"
      },
      {
        id:3,
        backup: 'Harpriya Singh',
        role: 'Project Lead',
        email: "bidoya2@gmail.com",
        Bid: "#Bid3442",
        qt: "10K",
        Date: `21-11-2021`,
        Date2: `12-01-2021`,
        name: "Komal",
        budget: "200K",
        avatar:"",
        rating: 6.75,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"Company WaterMark"
      },
      {
        id:4,
        backup: 'Surya Das',
        role: 'Project Lead',
        email: "bidoya3@gmail.com",
        Bid: "#Bid3452",
        qt: "2K",
        Date: `21-11-2021`,
        Date2: `12-01-2021`,
        name: "Mehul",
        budget: "200K",
        avatar:'',
        rating: 6.5,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"Logo of team"
      },
      {
        id:5,
        backup: 'Komal Jadhav',
        role: 'Project Lead',
        email: "bidoya4@gmail.com",
        Bid: "#Bid3433",
        qt: "0.4K",
        Date: `21-11-2021`,
        Date2: `12-01-2021`,
        name: "Harpriya",
        budget: "200K",
        avatar:"",
        rating: 2,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"differnt Color"
      },
      {
        id:6,
        backup: 'Pravin Patil',
        role: 'Employee',
        email: "bidoya5@gmail.com",
        Bid: "#Bid6432",
        qt: "4K",
        Date: `21-11-2021`,
        Date2: `12-01-2021`,
        name: "Sneha",
        budget: "200K",
        avatar:"",
        rating: 9,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"Company WaterMark"
      },
      {
        id:7,
        backup: 'Pravin Patil',
        role: 'Employee',
        email: "bidoya6@gmail.com",
        Bid: "#Bid7432",
        qt: "12K",
        Date: `21-11-2021`,
        Date2: `12-01-2021`,
        name: "Vijay",
        budget: "200K",
        avatar:"",
        rating: 10,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"Company WaterMark"
      },
      {
        id:8,
        backup: 'Pravin Patil',
        role: 'Employee',
        email: "bidoya7@gmail.com",
        Bid: "#Bid3452",
        qt: "210K",
        Date: `21-11-2021`,
        Date2: `12-01-2021`,
        name: "Vanita",
        budget: "200K",
        avatar:"",
        rating: 2,
        transaction: 200000,
        balance: 30000,
        review:"Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"Logo of team"
      },
      {
        id:9,
        backup: 'Pravin Patil',
        role: 'Employee',
        email: "bidoya32@gmail.com",
        Bid: "#Bid3672",
        qt: "30K",
        Date: `21-11-2021`,
        Date2: `12-01-2021`,
        name: "Dhavde",
        budget: "200K",
        avatar:"",
        rating: 2.0,
        transaction: 200000,
        balance: 30000,
        review: "Your product is really good but still it's out of price range and also we can't add much customizations",
        customizations :"Company WaterMark"
      }
]
